### ISSUE TITLE
erleans_stream_manager breaks erleans_provider contract for all

### ISSUE THREAD

**Issue by Licenser** [GOFactory/erleans#18]
the contract for `all/1` is defined  as `{ok, [...]}`:
https://github.com/GOFactory/erleans/blob/master/src/erleans_provider.erl#L29

however this expects a return of `[...]`:
https://github.com/GOFactory/erleans/blob/master/src/erleans_stream_manager.erl#L146

**Comment by tsloughter** [comment]
Fixed with #19
